export const DB_NAME = "studentManagementMongoDBBackend";

export const feeDetailsMapping = (column) => ({
    serialNumber: column["S.N."],
    availingHostel: column["Availing Hostel Facility"],
    idNumber: column["ID Number"],
    candidateName: column["Name of the Candidate"],
    academicSession: column["Academic Session"],
    program: column["Program"],
    semester: column["Semester"],
    category: column["Category"],
    admissionFee: Number(column["Admission Fee"] || 0),
    idCardFee: Number(column["ID Card and Certificates Fee"] || 0),
    libraryFee: Number(column["Library Fee"] || 0),
    celebrationFee: Number(column["Celebration Fee"] || 0),
    placementFee: Number(column["Training & Placement Fee"] || 0),
    alumniMembership: Number(column["Alumni Life Membership"] || 0),
    cautionMoneyDeposit: Number(column["Caution Money Deposite"] || 0),
    registrationFee: Number(column["Registration Fee"] || 0),
    tuitionFee: Number(column["Tuition Fee"] || 0),
    coSAFee: Number(column["CoSA Fee"] || 0),
    healthFacility: Number(column["Health Facility Charges"] || 0),
    otherFee: Number(column["Other Fee"] || 0),
    studentWelfareFund: Number(column["Student Welfare Fund (Not Fee)"] || 0),
    insurancePremium: Number(column["Insurance Premium"] || 0),
    hostelAdmissionFee: Number(column["Hostel Admission Fee"] || 0),
    hostelLicenseFee: Number(column["Hostel License Fee"] || 0),
    establishmentCharges: Number(column["Hostel and Mess Establishment Charges"] || 0),
    diningCharges: Number(column["Dinning Charges"] || 0),
    grossTotalFee: Number(column["Gross Total Fee"] || 0),
    feeWaiver: Number(column["Fee Waiver"] || 0),
    feeAdjustment: Number(column["Seat Booking/ Dining Fee Adjustment"] || 0),
    payableFee: Number(column["Payable Fee"] || 0),
});